### ISSUE TITLE
Help Page Link broken

### ISSUE THREAD

**Issue by rallek** [zikula-modules/MediaModule#100]
![grafik](https://user-images.githubusercontent.com/935250/52271069-f1a1bd80-2942-11e9-98de-29f6c33a2120.png)
the link is giving a 404

**Comment by rallek** [comment]
![grafik](https://user-images.githubusercontent.com/935250/87221256-d83c4680-c36a-11ea-8bb8-800aea2a5865.png)
Just change the link to github as long there is no other helping page

**Comment by Guite** [comment]
Or use the new extension help feature offered by Zikula core 3.
