### ISSUE TITLE
Can not install;core 2.0.12; Mediamodule -2.0.0

### ISSUE THREAD

**Issue by shoshia** [zikula-modules/MediaModule#104]
It takes long time after clicking on install and finally error 500 appears.
phpmyadmin shows mediamodule in modules table. Extensions tab shows as uninstalled.
----------------------
I need simple file/image uploader...Can someone update KCfinder [](https://github.com/nmpetkov/Kcfinder-zk) for 2.x?
[https://github.com/nmpetkov/Kcfinder-zk](url)

**Comment by Guite** [comment]
Please delete all media module from your database, set `debug: true` in `app/config/custom_parameters.yml`, repeat the instlalation and post the error stack trace here.

**Comment by shoshia** [comment]
I found problem...When extracted in modules dir, there was nesting dirs in mediashare whith dir 'modules'.
It works fine now..
In admin panel it says that scribite intergration is Ok, but i dont see integration ...what is means and how it integrates....
p.s.
I got ckeditor working see scribite project...Just copyed by hand needed file in web directory.
Can you consider adding kcfinedr plugin i mentioned above? or can you give me some directions how to add? zikula plugins are gon right? everything needs to be module?

**Comment by Guite** [comment]
Integration: both Content and Media offer CKEditor plugins. To enable these change your toolbar to _Special 1_ on CKEditor configuration page. Afterwards copy the attached file into `web/editors/ckeditor/ckeditor/custconfig.js`.

[custconfig.js.txt](https://github.com/zikula-modules/MediaModule/files/2897650/custconfig.js.txt)

To add additional plugins basically download them, copy into `web/editors/ckeditor/ckeditor/plugins/` and enable in same file.

Yes, system plugins and module plugins are gone.

This was the last time I answer your support questions on GitHub. We have support channels in Slack you should use instead. See https://ziku.la/en/support.html
