### ISSUE TITLE
Importer: DownloadsModuleImporter is not working

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/MediaModule#105]
ZK: 2.0.12
Mediamodule: 2.0.1 Masterbranch

Try import from Downloads module, but I got the error: `Call to a member function setUpdatedDate() on null`. in the file `cmfcmf\media-module\Importer\DownloadsModuleImporter.php`L117.
(Updated post)
I have been able to fix this. This don't work
```
$entity
....
->setCreatedDate(new \DateTime($download['ddate']))
->setUpdatedDate(new \DateTime($download['uupdate']));
```
You can fix this so (simple):
```
$entity
....
->setCreatedDate(new \DateTime($download['ddate']));
$entity
->setUpdatedDate(new \DateTime($download['uupdate']));
```

Really, I dont understand why dont work, but...
Thanks

**Comment by KratorD** [comment]
@Guite  finally, I have found how to solve this problem, can you take my correction to the code when you arrived? I have updated the main thread.

**Comment by Guite** [comment]
Thanks.
