### ISSUE TITLE
Symbols and Watermark are not shown in Gallery

### ISSUE THREAD

**Issue by rallek** [zikula-modules/MediaModule#171]
![grafik](https://user-images.githubusercontent.com/935250/87246099-46583a80-c44b-11ea-9904-c8fd03c70336.png)

This are my settings:
![grafik](https://user-images.githubusercontent.com/935250/87246069-03966280-c44b-11ea-91c0-42d16307e95b.png)

Watermark is text based

**Comment by rallek** [comment]
Watermark might be related to #172

**Comment by Guite** [comment]
Missing symbols was already fixed in the core by https://github.com/zikula/core/commit/b4298a0117a2e382308883be84b326b95d88f3ce

So all done here.
