### ISSUE TITLE
problem with language

### ISSUE THREAD

**Issue by rallek** [zikula-modules/MediaModule#90]
I do have a site with zk1.4.4 and MM 1.2.2. The site is running normally in German language. As soon as I go to the MM backend (the german URL is not working) the hl cookie is switching to en!

is that related to https://github.com/zikula/core/issues/3224?

**Comment by rallek** [comment]
additional info. MM is always and everywhere in English

**Comment by Guite** [comment]
This can probably be closed @rallek  ?

**Comment by rallek** [comment]
seems to be solved
