### ISSUE TITLE
Its not possible install in ZK2

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/MediaModule#95]
ZK2.0.7
Media-Module: master branch

When I try install the extension, i got an error: `The file "C:\xampp\htdocs\zk201\modules\cmfcmf\media-module\DependencyInjection/../Resources/config\services.yml" does not contain valid YAML.`

**Comment by Guite** [comment]
Just fixing the YAML files is not enough for ZK2. The module needs to refactor away many legacy usages, like CategoryUtil, FileUtil, old StandardFields and others.

**Comment by cmfcmf** [comment]
@KratorD I've read on Slack that you are working on upgrading the module. That's great news! Let me know when you make progress 💯

**Comment by KratorD** [comment]
Correct @cmfcmf . I only was waiting know if you will convert the media-module to zk2, because you did a good work and I want use this module in the future ;)
Thanks, i hope that you can test zk2 and upgrade the module to this cool version.
